export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const SAVE_PRICE_RANGE = "SAVE_PRICE_RANGE";
export const SAVE_COLORS = "SAVE_COLORS";
export const SAVE_CATEGORY_ID = "SAVE_CATEGORY_ID";
export const SAVE_CURRENT_PAGE = "SAVE_CURRENT_PAGE";
